/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almaceninventario;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows 10
 */
public class BuscarNombre extends javax.swing.JFrame {

    private String UltimaBusqueda = "";

    public BuscarNombre() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnLimpiarTabla = new javax.swing.JButton();
        btnLimpiarTabla1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Producto por Nombre");

        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jButton1.setText("Menu Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar por Nombre del Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtBusqueda.setToolTipText("Ingresa el codigo que deseas buscar.");
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo", "Descripcion", "Existencias", "Estado del Producto", "Fecha de Ingreso", "Precio de Compra", "Precio de venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Nombre");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Codigo");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Descripcion");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Existencias");
        }

        btnLimpiarTabla.setText("Limpiar la tabla");
        btnLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTablaActionPerformed(evt);
            }
        });

        btnLimpiarTabla1.setText("Guardar cambios");
        btnLimpiarTabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTabla1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 242, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnLimpiarTabla)
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addGap(48, 48, 48)
                .addComponent(btnLimpiarTabla1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnSalir)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnLimpiarTabla)
                    .addComponent(btnLimpiarTabla1))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ModificarProducto ModificarProducto = new ModificarProducto();
        ModificarProducto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();//cargamos la referencia de la tabla a la memoria
        ArchivoProductos ArchivoProductos = new ArchivoProductos("Productos.txt");//cargamos los productos
        ArchivoProductos.LeerProductos();// a la memoria, esto lee lo almacenado en el fichero
        if (!txtBusqueda.getText().isEmpty()) {//Se verifica si el campo de busqueda no esta vacio
            if (tabla.getRowCount() > 0) {//si no esta vacio procede a verificar si hay productos en la tabla
                while (tabla.getRowCount() > 0) {//de ser asi limpia latabla antes de imprimir nueva informacion
                    tabla.removeRow(0);//Elimmina la primera fila hasta que ya no hay mas filas
                }
            }
            /*
            El for que esta acontinuacion va comparando si los productos cumplen con el mismo nombre
            de lo contrario son ignorados y por ende no son mostrados en la tabla.
            TANTO ELIMINAR, COMO ACTUALIZAR YA SEA POR CODIGO O POR NOMBRE SE UTILIZA ESTE METODO PARA DESPLEGAR LAS FILAS
            */
            
            for (Producto producto : ArchivoProductos.Productos) {//Una vez que la tabla se limpio
                if (producto.Nombre.matches(txtBusqueda.getText())) {// se cargan los productos uno por uno
                    Object[] row = {producto.Nombre,//y se almacena su informacion individual en una sola
                        producto.Codigo,//variable la cual va a ser utilizada para agregar una fila a la tabla
                        producto.Descripcion,
                        producto.Existencias,
                        producto.EstadoProducto,
                        producto.FechaIngreso,
                        producto.PrecioCompra,
                        producto.PrecioVenta};
                    tabla.addRow(row);//una vez creada la variabla se procede a agregar la fila a la tabla

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tienes que colocar una palabra para buscar", "Error", JOptionPane.ERROR_MESSAGE);//en caso de que no 
            //haya ningun texto en la barra de busqueda se muestra un mensaje a tomar en consideracion.
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTablaActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();//para limpiar la tabla con un boton se 
        if (tabla.getRowCount() > 0) {//realiza el mismo procedimiento, mientras hayan filas en la tabla
            while (tabla.getRowCount() > 0) {//se va a ir eliminando la primera hasta que no quede ninguna
                tabla.removeRow(0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "La tabla ya se encuentra limpia", "Info", JOptionPane.INFORMATION_MESSAGE);//si se trata
            //de limpiar la tabla cuando ya esta limpia esta mostrara un mensaje.
        }
    }//GEN-LAST:event_btnLimpiarTablaActionPerformed

    private void btnLimpiarTabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTabla1ActionPerformed
        ArchivoProductos ArchivoProductos = new ArchivoProductos("Productos.txt");// para guardar las modificaciones se abre el fichero 
        ArchivoProductos.LeerProductos();//se carga en memoria toda su informacion
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();// se crea una referencia de la tabla
        if (tabla.getRowCount() > 0) {//se verifica que haya filas
            while (tabla.getRowCount() > 0) {//mientras haya filas disponibles
                for (int i = 0; i < ArchivoProductos.Productos.size(); i++) {//se va a buscar entre todos los productos 
                    if (ArchivoProductos.Productos.get(i).FechaIngreso.equalsIgnoreCase((String) tabla.getValueAt(0, 5))) {//al que coincida con
                        ArchivoProductos.Productos.get(i).Nombre = (String)tabla.getValueAt(0,0);//la fecha de creacion,
                        ArchivoProductos.Productos.get(i).Codigo = (String)tabla.getValueAt(0,1);//y de esta manera, se actualiza los datos en memoria
                        ArchivoProductos.Productos.get(i).Descripcion = (String)tabla.getValueAt(0,2);//actualizamos la priemra fila
                        ArchivoProductos.Productos.get(i).Existencias = (String)tabla.getValueAt(0,3);//y eso lo hacemos actualizando todas sus 
                        ArchivoProductos.Productos.get(i).EstadoProducto = (String)tabla.getValueAt(0,4);//columnas al mismo tiempo
                        ArchivoProductos.Productos.get(i).PrecioCompra = (String)tabla.getValueAt(0,6);
                        ArchivoProductos.Productos.get(i).PrecioVenta = (String)tabla.getValueAt(0,7);
                    }
                }
                ArchivoProductos.EscribirProductos(false);//una vez todos los datos son actualizados se guarda en el fichero los 
                //cambios que se hicieron en la memoria
                tabla.removeRow(0);//se elimina la fila que recien acabamos de actualizar y se sigue buscando actualizar las siguientes filas
                
            }
            JOptionPane.showMessageDialog(null, "Los productos han sido actualizados", "Info", JOptionPane.INFORMATION_MESSAGE);//una vez los datos han sido actualizados
            //se informa mediante un mensaje que se ha logrado actualizar los datos de manera satisfactoria
        }
    }//GEN-LAST:event_btnLimpiarTabla1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarNombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiarTabla;
    private javax.swing.JButton btnLimpiarTabla1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
