/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almaceninventario;

/**
 *
 * @author Windows 10
 */
public class IngresoUsuarios extends javax.swing.JFrame {

    private String TipoUsuario = "nulo"; //creamos una variable que guarda si algun usuario esta logueado

    /**
     * Creates new form IngresoUsuarios
     */
    public IngresoUsuarios() {//en caso de que no se le pase ningun parametro al constructor
        TipoUsuario = "nulo";// se asume que nadie esta logueado aun
        initComponents();
    }

    public IngresoUsuarios(String TipoUsuario) {// cuando se le pasa la 
        this.TipoUsuario = TipoUsuario;//variable al constructor es porque hay alguien que ya se logueo
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnBodega = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnSalirUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setText("INVENTARIO DEL ALMACEN");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mi pinturita bonita");

        jLabel3.setText("SELECCIONE EL TIPO DE USUARIO");

        btnAdmin.setText("ADMIN.");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnVentas.setText("VENTAS");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnBodega.setText("BODEGA");
        btnBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBodegaActionPerformed(evt);
            }
        });

        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnUsuarios.setText("USUARIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnSalirUsuarios.setText("SALIR");
        btnSalirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdmin)
                        .addGap(74, 74, 74)
                        .addComponent(btnVentas)
                        .addGap(73, 73, 73)
                        .addComponent(btnBodega))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnReportes)
                        .addGap(76, 76, 76)
                        .addComponent(btnUsuarios)))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalirUsuarios)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(311, 311, 311))))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmin)
                    .addComponent(btnVentas)
                    .addComponent(btnBodega))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportes)
                    .addComponent(btnUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnSalirUsuarios)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        if (TipoUsuario.equalsIgnoreCase("Administrador")) {//cuando presionamos el boton de admin
            GestionProductos GestionProductos = new GestionProductos();//se verifica si hay algun admin logueado
            GestionProductos.setVisible(true);//de ser asi nos mueve al apartado de productos disponible solo
            this.setVisible(false);//para los admins y luego oculta la ventana actual
        } else {// pero en dado caso que no haya un admin logueado se procede a
            AccesoUsuarios AccesoUsuarios = new AccesoUsuarios("Admin");//redirigir a la ventana de inicion de sesion de admin
            /* Se le esta pasando un parametro a Accesousuario para
            indicarle que cuando el usuario se haya logueado 
            este sea enviado a la pagina del admin, la cual 
            es la principal
            dado que tiene permiso para todo*/
            AccesoUsuarios.setVisible(true);
            this.setVisible(false);//y se oculta la ventana actual
        }
    }//GEN-LAST:event_btnAdminActionPerformed
//Aqui se realiza lo mismo que en el anterior boton, verificamos si hay algun admin que este logueado
    //de lo contrario mandamos al logueo de usuarios de ventas, este redirige directamente a ventas.
    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        if (TipoUsuario.equalsIgnoreCase("Administrador")) {//verificamos si hay algun admi
            GestionVentas GestionVentas = new GestionVentas();
            GestionVentas.setVisible(true);
            this.setVisible(false);
        } else {
            AccesoUsuarios AccesoUsuarios = new AccesoUsuarios("Ventas");
            AccesoUsuarios.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnSalirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirUsuariosActionPerformed
        ingreso Volver = new ingreso();//boton de regreso a la ventana anterior
        Volver.setVisible(true);
        this.setVisible(false);//ocultamos la ventana actual

    }//GEN-LAST:event_btnSalirUsuariosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        MenuUsuarios Usuarios = new MenuUsuarios();//la ventana usuarios donde
        Usuarios.setVisible(true);//se gestiona usuarios
        this.setVisible(false);//ocultamos la ventana actual.


    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        if (TipoUsuario.equalsIgnoreCase("Administrador")){//el mismo proceso se aplica a Reportes y bodega
            GestionReportes GestionReportes = new GestionReportes();
            GestionReportes.setVisible(true);
            this.setVisible(false);
        } else {
            AccesoUsuarios AccesoUsuarios = new AccesoUsuarios("Reportes");
            AccesoUsuarios.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBodegaActionPerformed
        if (TipoUsuario.equalsIgnoreCase("Administrador")) {// si no hay usuario solicitar uno
            GestionBodega GestionBodega = new GestionBodega();//al accesar te dirije al unico area autorizado
            GestionBodega.setVisible(true);
            this.setVisible(false);
        } else {
            AccesoUsuarios AccesoUsuarios = new AccesoUsuarios("Bodega");
            AccesoUsuarios.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnBodegaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoUsuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnBodega;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalirUsuarios;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
